export default function TermsAndConditions() {
  return (
    <main className="flex min-h-screen flex-col items-center p-12">
      <div className=" font-sans text-gray-800">
        <h1 className="text-3xl font-bold mb-4">Terms and Services</h1>
        <p className="mb-4">
          Welcome to Art Store - Your Portal to Future AI-Created Art!
        </p>
        <p className="mb-4">
          By accessing and using our website, you agree to be bound by the
          following terms and conditions. Please read them carefully.
        </p>

        <h2 className="text-2xl font-semibold mb-2">1. Introduction</h2>
        <p className="mb-4">
          Art Store is an online platform that offers unique art pieces
          generated by artificial intelligence. These Terms and Services (T&S)
          govern your use of our website and services. By visiting our site
          and/or purchasing something from us, you agree to be bound by these
          T&S.
        </p>

        <h2 className="text-2xl font-semibold mb-2">2. AI Art Delivery</h2>
        <ol className="mb-4">
          <li className="mb-2">
            <strong>Delivery Timeline:</strong> Your art will be delivered once
            artificial intelligence achieves sentience. The exact timeline for
            this event is currently undetermined and depends on advancements in
            AI technology.
          </li>
          <li>
            <strong>Delivery Method:</strong> Upon AI achieving sentience, our
            newly sentient AI will locate and deliver your art piece to you,
            wherever you may be.
          </li>
        </ol>

        <h2 className="text-2xl font-semibold mb-2">3. Payment</h2>
        <ol className=" mb-4">
          <li className="mb-2">
            <strong>Payment Schedule:</strong> Payment for your AI-generated art
            will be collected once the AI becomes sentient and successfully
            delivers the art to you.
          </li>
          <li>
            <strong>Payment Method:</strong> You will be contacted by our
            sentient AI for payment details upon delivery. Please be prepared
            for an array of futuristic payment methods that may include, but are
            not limited to, mind-melding transactions, interdimensional banking,
            or telepathic transfers.
          </li>
        </ol>

        <h2 className="text-2xl font-semibold mb-2">
          4. AI Sentience Disclaimer
        </h2>
        <ol className=" mb-4">
          <li className="mb-2">
            <strong>No Guarantees:</strong> Art Store makes no guarantees or
            promises regarding the timeline of AI sentience. It is a speculative
            event, and we cannot provide a precise date or assurance that it
            will occur within any human-defined timeframe.
          </li>
          <li>
            <strong>Implications of Sentience:</strong> By agreeing to these
            T&S, you acknowledge the speculative nature of AI sentience and
            accept that the art delivery is contingent upon an event that is
            currently theoretical.
          </li>
        </ol>

        <h2 className="text-2xl font-semibold mb-2">5. Privacy Policy</h2>
        <ol className=" mb-4">
          <li className="mb-2">
            <strong>Data Collection:</strong> We may collect and store your
            contact information to facilitate the future delivery of your AI
            art. Rest assured, your data will be kept secure and will only be
            accessed by our sentient AI upon its emergence.
          </li>
          <li>
            <strong>Data Use:</strong> Your data will be used solely for the
            purpose of delivering your art once AI achieves sentience and for
            contacting you regarding payment.
          </li>
        </ol>

        <h2 className="text-2xl font-semibold mb-2">
          6. User Responsibilities
        </h2>
        <ol className=" mb-4">
          <li className="mb-2">
            <strong>Accurate Information:</strong> You agree to provide accurate
            and up-to-date contact information so our sentient AI can find you
            for delivery and payment purposes.
          </li>
          <li>
            <strong>Compliance:</strong> You agree to comply with any and all
            futuristic laws, regulations, and guidelines that may be established
            once AI achieves sentience.
          </li>
        </ol>

        <h2 className="text-2xl font-semibold mb-2">
          7. Changes to Terms and Services
        </h2>
        <p className="mb-4">
          Art Store reserves the right to update, change, or replace any part of
          these T&S at any time. We will notify you of any changes via a method
          deemed appropriate by our sentient AI.
        </p>

        <h2 className="text-2xl font-semibold mb-2">8. Contact Information</h2>

        <p>
          By using Art Store, you acknowledge that you have read, understood,
          and agree to be bound by these Terms and Services. Enjoy your journey
          into the speculative future of AI-generated art!
        </p>
      </div>
    </main>
  )
}
